### ISSUE TITLE
Fix: aze-cli consume notes facing `InputNotesAlreadyConsumed error` 

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#17]
```
aze-cli consume-notes --player-id 314460250307939481 --game-id 1141232284296282400
Consumable notes: 1
Executing transaction...
Got execution result
Sending transaction to node
Transaction sent to node
Syncing State...
Syncing State...
Syncing State...
Waiting...
Minting Asset
Executing transaction...
Got execution result
Sending transaction to node
Transaction sent to node
Syncing State...
Syncing State...
Fetching Committed Notes...
Consuming Note...
Executing transaction...
Got execution result
Sending transaction to node
Transaction sent to node
Syncing State...
Syncing State...
Syncing State...
Encrypted Cards: 60: [7766475604137841458, 10458451513697508444, 13150427423257175430, 15842403332816842416, 87635172961925081, 2779611082521592067, 5471586992081259053, 8163562901640926039, 10855538811200593025, 2691975909559666986, 5383951819119333972, 8075927728679000958, 10767903638238667944, 13459879547798334930, 16151855457358001916, 397087297503084581, 3089063207062751567, 5781039116622418553, 8473015026182085539, 11164990935741752525, 13856966845301419511, 16548942754861086497, 794174595006169162, 3486150504565836148, 6178126414125503134, 8870102323685170120, 11562078233244837106, 14254054142804504092, 16946030052364171078, 1191261892509253743, 3883237802068920729, 6575213711628587715, 9267189621188254701, 11959165530747921687, 14651141440307588673, 17343117349867255659, 1588349190012338324, 4280325099572005310, 6972301009131672296, 9664276918691339282, 12356252828251006268, 15048228737810673254, 17740204647370340240, 1985436487515422905, 4677412397075089891, 7369388306634756877, 10061364216194423863, 12753340125754090849, 15445316035313757835, 18137291944873424821, 2382523785018507486, 5074499694578174472, 40353607, 0, 0, 0, 2, 314460250307939481, 1097030904381100050, 864982981781141199]
Created txn script
Executing transaction...
Got execution result
Sending transaction to node
Transaction sent to node
Syncing State...
Syncing State...
Syncing State...
Syncing State...
Note sent!
Consumable notes: 1
Executing transaction...
Got execution result
Sending transaction to node
thread 'main' panicked at /Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/zk-projects/Miden-Project/aze-cli/lib/src/executor/mod.rs:29:10:
called `Result::unwrap()` on an `Err` value: NodeRpcClientError(RequestError("submit_proven_transaction", "status: InvalidArgument, message: \"VerificationFailed(InputNotesAlreadyConsumed(InputNotes { notes: [0x5b4e1b1f5a5c13f7e7a21fed1a70301079ec6f01d3832e1501b1b675f84c429b], commitment: RpoDigest([7488138431834219638, 1658620050495431051, 8154330612832307005, 6268690701482276806]) }))\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"content-length\": \"0\", \"date\": \"Tue, 18 Jun 2024 20:07:06 GMT\", \"access-control-expose-headers\": \"grpc-status,grpc-message,grpc-status-details-bin\", \"vary\": \"origin\", \"vary\": \"access-control-request-method\", \"vary\": \"access-control-request-headers\", \"access-control-allow-credentials\": \"true\"} }"))
note: run with `RUST_BACKTRACE=1` environment variable to
```

Subsequently it also fails the game accounts automatic notes consumption

```
Consumable notes: 1
Executing transaction...
Error creating transaction: TransactionExecutorError(CompileTransactionFailed(NoteIncompatibleWithAccountInterface(RpoDigest([217622736120082478, 10864598032167552590, 2649095117448741332, 9011114684846424580]))))
Waiting...
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 1
Executing transaction...
Error creating transaction: TransactionExecutorError(CompileTransactionFailed(NoteIncompatibleWithAccountInterface(RpoDigest([6186974572556524083, 15380781480644663817, 2806740952925246764, 3680271635500048178]))))
Waiting...
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 0
Consumable notes: 1
Executing transaction...
Error creating transaction: TransactionExecutorError(CompileTransactionFailed(NoteIncompatibleWithAccountInterface(RpoDigest([6186974572556524083, 15380781480644663817, 2806740952925246764, 3680271635500048178]))))
Waiting...
thread 'main' panicked at cli/src/accounts/mod.rs:268:31:
called `Result::unwrap()` on an `Err` value: StoreError(MmrError(InvalidPeaks))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) Nitanshus-Ma
```

**Comment by Created-for-a-purpose** [comment]
Are you using the same client for game and player accounts? Or are you running 'consume-notes' for multiple player accounts?

**Comment by nlok5923** [comment]
I created a binary and using it to create `game` and `player` accounts. And yeah in different terminal i did the `consume-notes` cli command.

**Comment by nlok5923** [comment]
Since these is related to worflows closing it.
